version: '3.9'

services:
  web:
    container_name: pvpoketw
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PVPOKE_PORT:-80}:80" # Use port set in PVPOKE_PORT env variable, use port 80 as default
    volumes:
      - ../src:/var/www/html/pvpoketw/src
